server:
  port: 1111

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/ashokitschool/configuration_properties
          clone-on-start: true
          
management:
  endpoints:
    web:
      exposure:
        include: '*'